import {
  type NotificationCategory,
  type ExternalNotificationChannel,
  type NotificationChannel,
  type NotificationRoutingRule,
  type NotificationUrgency,
} from "./types";

function rule(
  eventType: string,
  label: string,
  category: NotificationCategory,
  urgency: NotificationUrgency,
  preferredChannels: readonly NotificationChannel[],
  templateKey: string,
  notes?: string,
  safetyBypass = false,
  quietHoursBypass = false,
  suppressionBypass = false,
): NotificationRoutingRule {
  return {
    eventType,
    label,
    category,
    urgency,
    preferredChannels,
    templateKey,
    notes,
    safetyBypass,
    quietHoursBypass,
    suppressionBypass,
  };
}

export const NOTIFICATION_ROUTING_RULES: readonly NotificationRoutingRule[] = [
  rule(
    "tour_requested",
    "Tour requested",
    "tours",
    "transactional",
    ["in_app", "push", "sms", "email"],
    "tour_requested",
  ),
  rule(
    "tour_confirmed",
    "Tour confirmed",
    "tours",
    "transactional_must_deliver",
    ["in_app", "push", "sms", "email"],
    "tour_confirmed",
  ),
  rule(
    "tour_canceled",
    "Tour canceled",
    "tours",
    "transactional_must_deliver",
    ["in_app", "push", "sms", "email"],
    "tour_canceled",
  ),
  rule(
    "tour_reminder",
    "Tour reminder",
    "tours",
    "transactional_must_deliver",
    ["push", "sms", "email"],
    "tour_reminder",
  ),
  rule(
    "tour_rescheduled",
    "Tour rescheduled",
    "tours",
    "transactional",
    ["in_app", "push", "sms", "email"],
    "tour_rescheduled",
  ),
  rule(
    "tour_check_in",
    "Tour check-in",
    "tours",
    "transactional",
    ["in_app", "push"],
    "tour_check_in",
  ),
  rule(
    "tour_feedback_requested",
    "Tour feedback requested",
    "tours",
    "relationship",
    ["in_app", "email"],
    "tour_feedback_requested",
  ),
  rule(
    "tour_feedback_received",
    "Tour feedback received",
    "tours",
    "relationship",
    ["in_app"],
    "tour_feedback_received",
  ),
  rule(
    "agent_assigned",
    "Agent assigned",
    "transactional",
    "transactional_must_deliver",
    ["in_app", "push", "sms", "email"],
    "agent_assigned",
  ),
  rule(
    "agent_unassigned",
    "Agent unassigned",
    "transactional",
    "transactional",
    ["in_app", "email"],
    "agent_unassigned",
  ),
  rule(
    "agent_message",
    "Agent message",
    "transactional",
    "relationship",
    ["in_app", "push", "sms", "email"],
    "agent_message",
  ),
  rule(
    "broker_message",
    "Broker message",
    "transactional",
    "transactional_must_deliver",
    ["in_app", "push", "sms", "email"],
    "broker_message",
  ),
  rule(
    "broker_follow_up_due",
    "Broker follow-up due",
    "transactional",
    "relationship",
    ["in_app", "push", "email"],
    "broker_follow_up_due",
  ),
  rule(
    "buyer_note_added",
    "Buyer note added",
    "transactional",
    "relationship",
    ["in_app", "email"],
    "buyer_note_added",
  ),
  rule(
    "offer_draft_ready",
    "Offer draft ready",
    "offers",
    "transactional",
    ["in_app", "push", "email"],
    "offer_draft_ready",
  ),
  rule(
    "offer_ready_for_review",
    "Offer ready for review",
    "offers",
    "transactional",
    ["in_app", "push", "email"],
    "offer_ready_for_review",
  ),
  rule(
    "offer_submitted",
    "Offer submitted",
    "offers",
    "transactional_must_deliver",
    ["in_app", "push", "sms", "email"],
    "offer_submitted",
  ),
  rule(
    "offer_countered",
    "Offer countered",
    "offers",
    "transactional_must_deliver",
    ["in_app", "push", "sms", "email"],
    "offer_countered",
  ),
  rule(
    "offer_accepted",
    "Offer accepted",
    "offers",
    "transactional_must_deliver",
    ["in_app", "push", "sms", "email"],
    "offer_accepted",
  ),
  rule(
    "offer_rejected",
    "Offer rejected",
    "offers",
    "transactional_must_deliver",
    ["in_app", "push", "sms", "email"],
    "offer_rejected",
  ),
  rule(
    "offer_expiring",
    "Offer expiring",
    "offers",
    "transactional_must_deliver",
    ["push", "sms", "email"],
    "offer_expiring",
  ),
  rule(
    "offer_deadline_approaching",
    "Offer deadline approaching",
    "offers",
    "transactional",
    ["push", "email"],
    "offer_deadline_approaching",
  ),
  rule(
    "agreement_received",
    "Agreement received",
    "disclosures",
    "transactional_must_deliver",
    ["in_app", "push", "sms", "email"],
    "agreement_received",
  ),
  rule(
    "agreement_signed_reminder",
    "Agreement reminder",
    "disclosures",
    "transactional_must_deliver",
    ["push", "sms", "email"],
    "agreement_signed_reminder",
  ),
  rule(
    "agreement_signature_requested",
    "Agreement signature requested",
    "disclosures",
    "transactional_must_deliver",
    ["push", "sms", "email"],
    "agreement_signature_requested",
  ),
  rule(
    "agreement_expiring",
    "Agreement expiring",
    "disclosures",
    "transactional_must_deliver",
    ["push", "sms", "email"],
    "agreement_expiring",
  ),
  rule(
    "document_ready",
    "Document ready",
    "closing",
    "transactional",
    ["in_app", "push", "email"],
    "document_ready",
  ),
  rule(
    "document_requested",
    "Document requested",
    "closing",
    "transactional",
    ["in_app", "push", "email"],
    "document_requested",
  ),
  rule(
    "document_review_ready",
    "Document review ready",
    "closing",
    "transactional",
    ["in_app", "push", "email"],
    "document_review_ready",
  ),
  rule(
    "document_signature_requested",
    "Document signature requested",
    "closing",
    "transactional_must_deliver",
    ["push", "sms", "email"],
    "document_signature_requested",
  ),
  rule(
    "closing_clear_to_close",
    "Clear to close",
    "closing",
    "transactional_must_deliver",
    ["push", "sms", "email"],
    "closing_clear_to_close",
  ),
  rule(
    "closing_inspection_scheduled",
    "Closing inspection scheduled",
    "closing",
    "transactional",
    ["in_app", "push", "sms", "email"],
    "closing_inspection_scheduled",
  ),
  rule(
    "closing_funding_received",
    "Funding received",
    "closing",
    "transactional_must_deliver",
    ["push", "sms", "email"],
    "closing_funding_received",
  ),
  rule(
    "closing_funds_due",
    "Funds due",
    "closing",
    "transactional_must_deliver",
    ["push", "sms", "email"],
    "closing_funds_due",
  ),
  rule(
    "milestone_upcoming",
    "Milestone upcoming",
    "transactional",
    "transactional",
    ["in_app", "push", "email"],
    "milestone_upcoming",
  ),
  rule(
    "milestone_overdue",
    "Milestone overdue",
    "transactional",
    "transactional_must_deliver",
    ["in_app", "push", "sms", "email"],
    "milestone_overdue",
  ),
  rule(
    "milestone_completed",
    "Milestone completed",
    "transactional",
    "relationship",
    ["in_app", "email"],
    "milestone_completed",
  ),
  rule(
    "price_changed",
    "Price changed",
    "market_updates",
    "relationship",
    ["in_app", "push", "email"],
    "price_changed",
  ),
  rule(
    "price_drop_alert",
    "Price drop alert",
    "market_updates",
    "relationship",
    ["push", "email"],
    "price_drop_alert",
  ),
  rule(
    "price_increase_alert",
    "Price increase alert",
    "market_updates",
    "relationship",
    ["in_app", "email"],
    "price_increase_alert",
  ),
  rule(
    "new_comp_arrived",
    "New comp arrived",
    "market_updates",
    "relationship",
    ["in_app", "email"],
    "new_comp_arrived",
  ),
  rule(
    "comp_summarized",
    "Comp summarized",
    "market_updates",
    "relationship",
    ["in_app", "email"],
    "comp_summarized",
  ),
  rule(
    "market_update_weekly",
    "Weekly market update",
    "market_updates",
    "digest_only",
    ["email", "in_app"],
    "market_update_weekly",
  ),
  rule(
    "market_update_price_drop",
    "Market price drop",
    "market_updates",
    "relationship",
    ["push", "email"],
    "market_update_price_drop",
  ),
  rule(
    "market_update_new_listing",
    "Market new listing",
    "market_updates",
    "digest_only",
    ["email", "in_app"],
    "market_update_new_listing",
  ),
  rule(
    "ai_analysis_ready",
    "AI analysis ready",
    "transactional",
    "relationship",
    ["in_app", "push", "email"],
    "ai_analysis_ready",
  ),
  rule(
    "ai_analysis_failed",
    "AI analysis failed",
    "transactional",
    "transactional_must_deliver",
    ["in_app", "email"],
    "ai_analysis_failed",
  ),
  rule(
    "ai_analysis_review_requested",
    "AI review requested",
    "transactional",
    "relationship",
    ["in_app", "email"],
    "ai_analysis_review_requested",
  ),
  rule(
    "ai_summary_ready",
    "AI summary ready",
    "transactional",
    "relationship",
    ["in_app", "push", "email"],
    "ai_summary_ready",
  ),
  rule(
    "deal_room_activated",
    "Deal room activated",
    "transactional",
    "transactional",
    ["in_app", "push", "email"],
    "deal_room_activated",
  ),
  rule(
    "deal_room_muted",
    "Deal room muted",
    "transactional",
    "relationship",
    ["in_app", "email"],
    "deal_room_muted",
  ),
  rule(
    "document_upload_received",
    "Document upload received",
    "closing",
    "transactional",
    ["in_app", "email"],
    "document_upload_received",
  ),
  rule(
    "disclosure_request_received",
    "Disclosure request received",
    "disclosures",
    "transactional",
    ["in_app", "push", "email"],
    "disclosure_request_received",
  ),
  rule(
    "disclosure_packet_ready",
    "Disclosure packet ready",
    "disclosures",
    "transactional_must_deliver",
    ["push", "sms", "email"],
    "disclosure_packet_ready",
  ),
  rule(
    "disclosure_ack_needed",
    "Disclosure acknowledgement needed",
    "disclosures",
    "transactional_must_deliver",
    ["push", "sms", "email"],
    "disclosure_ack_needed",
  ),
  rule(
    "disclosure_ack_reminder",
    "Disclosure acknowledgement reminder",
    "disclosures",
    "transactional_must_deliver",
    ["push", "sms", "email"],
    "disclosure_ack_reminder",
  ),
  rule(
    "closing_title_update",
    "Closing title update",
    "closing",
    "transactional",
    ["in_app", "email"],
    "closing_title_update",
  ),
  rule(
    "closing_wire_instructions_ready",
    "Wire instructions ready",
    "closing",
    "transactional_must_deliver",
    ["push", "sms", "email"],
    "closing_wire_instructions_ready",
  ),
  rule(
    "closing_final_walkthrough",
    "Final walkthrough",
    "closing",
    "transactional",
    ["in_app", "push", "sms", "email"],
    "closing_final_walkthrough",
  ),
  rule(
    "closing_sign_off_requested",
    "Closing sign-off requested",
    "closing",
    "transactional_must_deliver",
    ["push", "sms", "email"],
    "closing_sign_off_requested",
  ),
  rule(
    "marketing_reengagement",
    "Marketing re-engagement",
    "marketing",
    "digest_only",
    ["email"],
    "marketing_reengagement",
  ),
  rule(
    "marketing_anniversary",
    "Anniversary reminder",
    "marketing",
    "digest_only",
    ["email"],
    "marketing_anniversary",
  ),
  rule(
    "marketing_feature_announcement",
    "Feature announcement",
    "marketing",
    "digest_only",
    ["email"],
    "marketing_feature_announcement",
  ),
  rule(
    "marketing_weekly_digest",
    "Weekly digest",
    "marketing",
    "digest_only",
    ["email", "in_app"],
    "marketing_weekly_digest",
  ),
  rule(
    "safety_critical_alert",
    "Safety critical alert",
    "safety",
    "transactional_must_deliver",
    ["email", "sms", "push"],
    "safety_critical_alert",
    "Server-side bypass for life-safety or broker escalation notices.",
    true,
    true,
    true,
  ),
  rule(
    "safety_listing_issue",
    "Safety listing issue",
    "safety",
    "transactional_must_deliver",
    ["email", "sms", "push"],
    "safety_listing_issue",
    "Bypasses quiet hours and suppression when the broker flags a safety issue.",
    true,
    true,
    true,
  ),
  rule(
    "safety_broker_escalation",
    "Broker escalation",
    "safety",
    "transactional_must_deliver",
    ["email", "sms", "push"],
    "safety_broker_escalation",
    "Escalation notices are delivered even when the inbox is muted.",
    true,
    true,
    true,
  ),
];

export const NOTIFICATION_ROUTING_RULE_BY_EVENT_TYPE = new Map(
  NOTIFICATION_ROUTING_RULES.map((rule) => [rule.eventType, rule] as const),
);

export function getNotificationRoutingRule(
  eventType: string,
): NotificationRoutingRule | null {
  return NOTIFICATION_ROUTING_RULE_BY_EVENT_TYPE.get(eventType) ?? null;
}

export function isExternalNotificationChannel(
  channel: string,
): channel is ExternalNotificationChannel {
  return channel === "email" || channel === "sms" || channel === "push";
}

export function compareNotificationRoutingRules(
  a: NotificationRoutingRule,
  b: NotificationRoutingRule,
): number {
  if (a.urgency !== b.urgency) {
    return urgencyRank(b.urgency) - urgencyRank(a.urgency);
  }

  return a.eventType.localeCompare(b.eventType);
}

function urgencyRank(urgency: NotificationUrgency): number {
  switch (urgency) {
    case "transactional_must_deliver":
      return 4;
    case "transactional":
      return 3;
    case "relationship":
      return 2;
    case "digest_only":
      return 1;
  }
}
